# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import protos.book_catalog_pb2 as book__catalog__pb2

GRPC_GENERATED_VERSION = '1.65.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in book_catalog_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class BookCatalogStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBookInfo = channel.unary_unary(
                '/bookstore.BookCatalog/GetBookInfo',
                request_serializer=book__catalog__pb2.BookRequest.SerializeToString,
                response_deserializer=book__catalog__pb2.BookResponse.FromString,
                _registered_method=True)
        self.ListBooks = channel.unary_unary(
                '/bookstore.BookCatalog/ListBooks',
                request_serializer=book__catalog__pb2.Empty.SerializeToString,
                response_deserializer=book__catalog__pb2.BookList.FromString,
                _registered_method=True)


class BookCatalogServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBookInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookCatalogServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBookInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBookInfo,
                    request_deserializer=book__catalog__pb2.BookRequest.FromString,
                    response_serializer=book__catalog__pb2.BookResponse.SerializeToString,
            ),
            'ListBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBooks,
                    request_deserializer=book__catalog__pb2.Empty.FromString,
                    response_serializer=book__catalog__pb2.BookList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bookstore.BookCatalog', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bookstore.BookCatalog', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BookCatalog(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBookInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bookstore.BookCatalog/GetBookInfo',
            book__catalog__pb2.BookRequest.SerializeToString,
            book__catalog__pb2.BookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bookstore.BookCatalog/ListBooks',
            book__catalog__pb2.Empty.SerializeToString,
            book__catalog__pb2.BookList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
