# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book_catalog.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x62ook_catalog.proto\x12\tbookstore\"\x1c\n\x0b\x42ookRequest\x12\r\n\x05title\x18\x01 \x01(\t\"Y\n\x0c\x42ookResponse\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x0c\n\x04year\x18\x03 \x01(\x05\x12\r\n\x05stock\x18\x04 \x01(\x05\x12\r\n\x05price\x18\x05 \x01(\x02\"Q\n\x04\x42ook\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x0c\n\x04year\x18\x03 \x01(\x05\x12\r\n\x05stock\x18\x04 \x01(\x05\x12\r\n\x05price\x18\x05 \x01(\x02\"*\n\x08\x42ookList\x12\x1e\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x0f.bookstore.Book\"\x07\n\x05\x45mpty2\x81\x01\n\x0b\x42ookCatalog\x12>\n\x0bGetBookInfo\x12\x16.bookstore.BookRequest\x1a\x17.bookstore.BookResponse\x12\x32\n\tListBooks\x12\x10.bookstore.Empty\x1a\x13.bookstore.BookListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_catalog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOKREQUEST']._serialized_start=33
  _globals['_BOOKREQUEST']._serialized_end=61
  _globals['_BOOKRESPONSE']._serialized_start=63
  _globals['_BOOKRESPONSE']._serialized_end=152
  _globals['_BOOK']._serialized_start=154
  _globals['_BOOK']._serialized_end=235
  _globals['_BOOKLIST']._serialized_start=237
  _globals['_BOOKLIST']._serialized_end=279
  _globals['_EMPTY']._serialized_start=281
  _globals['_EMPTY']._serialized_end=288
  _globals['_BOOKCATALOG']._serialized_start=291
  _globals['_BOOKCATALOG']._serialized_end=420
# @@protoc_insertion_point(module_scope)
