# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_management.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16order_management.proto\x12\tbookstore\"D\n\x0cOrderRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12#\n\x05items\x18\x02 \x03(\x0b\x32\x14.bookstore.OrderItem\",\n\tOrderItem\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"!\n\rOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\"\x1b\n\x07OrderID\x12\x10\n\x08order_id\x18\x01 \x01(\t\"j\n\x0cOrderDetails\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12#\n\x05items\x18\x03 \x03(\x0b\x32\x14.bookstore.OrderItem\x12\x12\n\norder_date\x18\x04 \x01(\t\"\x19\n\x06UserID\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"7\n\x0cOrderHistory\x12\'\n\x06orders\x18\x01 \x03(\x0b\x32\x17.bookstore.OrderSummary\"0\n\x0cOrderSummary\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06titles\x18\x02 \x03(\t2\xd1\x01\n\x0fOrderManagement\x12?\n\nPlaceOrder\x12\x17.bookstore.OrderRequest\x1a\x18.bookstore.OrderResponse\x12>\n\x0fGetOrderDetails\x12\x12.bookstore.OrderID\x1a\x17.bookstore.OrderDetails\x12=\n\x0fGetOrderHistory\x12\x11.bookstore.UserID\x1a\x17.bookstore.OrderHistoryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_management_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERREQUEST']._serialized_start=37
  _globals['_ORDERREQUEST']._serialized_end=105
  _globals['_ORDERITEM']._serialized_start=107
  _globals['_ORDERITEM']._serialized_end=151
  _globals['_ORDERRESPONSE']._serialized_start=153
  _globals['_ORDERRESPONSE']._serialized_end=186
  _globals['_ORDERID']._serialized_start=188
  _globals['_ORDERID']._serialized_end=215
  _globals['_ORDERDETAILS']._serialized_start=217
  _globals['_ORDERDETAILS']._serialized_end=323
  _globals['_USERID']._serialized_start=325
  _globals['_USERID']._serialized_end=350
  _globals['_ORDERHISTORY']._serialized_start=352
  _globals['_ORDERHISTORY']._serialized_end=407
  _globals['_ORDERSUMMARY']._serialized_start=409
  _globals['_ORDERSUMMARY']._serialized_end=457
  _globals['_ORDERMANAGEMENT']._serialized_start=460
  _globals['_ORDERMANAGEMENT']._serialized_end=669
# @@protoc_insertion_point(module_scope)
