# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_authentication.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19user_authentication.proto\x12\tbookstore\"5\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\".\n\x0c\x41uthResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t2\x98\x01\n\x12UserAuthentication\x12\x43\n\x0cRegisterUser\x12\x1a.bookstore.RegisterRequest\x1a\x17.bookstore.AuthResponse\x12=\n\tLoginUser\x12\x17.bookstore.LoginRequest\x1a\x17.bookstore.AuthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_authentication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=40
  _globals['_REGISTERREQUEST']._serialized_end=93
  _globals['_LOGINREQUEST']._serialized_start=95
  _globals['_LOGINREQUEST']._serialized_end=145
  _globals['_AUTHRESPONSE']._serialized_start=147
  _globals['_AUTHRESPONSE']._serialized_end=193
  _globals['_USERAUTHENTICATION']._serialized_start=196
  _globals['_USERAUTHENTICATION']._serialized_end=348
# @@protoc_insertion_point(module_scope)
