# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_management.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16order_management.proto\x12\x06protos\"@\n\x0cOrderRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x0f\n\x07user_id\x18\x03 \x01(\t\"!\n\rOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\"\x1b\n\x07OrderID\x12\x10\n\x08order_id\x18\x01 \x01(\t\"O\n\x0cOrderDetails\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\"\x1e\n\x0bUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"\x1e\n\x0cOrderHistory\x12\x0e\n\x06titles\x18\x01 \x03(\t2\xc4\x01\n\x0fOrderManagement\x12\x39\n\nPlaceOrder\x12\x14.protos.OrderRequest\x1a\x15.protos.OrderResponse\x12\x38\n\x0fGetOrderDetails\x12\x0f.protos.OrderID\x1a\x14.protos.OrderDetails\x12<\n\x0fGetOrderHistory\x12\x13.protos.UserRequest\x1a\x14.protos.OrderHistoryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_management_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERREQUEST']._serialized_start=34
  _globals['_ORDERREQUEST']._serialized_end=98
  _globals['_ORDERRESPONSE']._serialized_start=100
  _globals['_ORDERRESPONSE']._serialized_end=133
  _globals['_ORDERID']._serialized_start=135
  _globals['_ORDERID']._serialized_end=162
  _globals['_ORDERDETAILS']._serialized_start=164
  _globals['_ORDERDETAILS']._serialized_end=243
  _globals['_USERREQUEST']._serialized_start=245
  _globals['_USERREQUEST']._serialized_end=275
  _globals['_ORDERHISTORY']._serialized_start=277
  _globals['_ORDERHISTORY']._serialized_end=307
  _globals['_ORDERMANAGEMENT']._serialized_start=310
  _globals['_ORDERMANAGEMENT']._serialized_end=506
# @@protoc_insertion_point(module_scope)
