# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_management.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16order_management.proto\x12\x0fordermanagement\"@\n\x0cOrderRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x0f\n\x07user_id\x18\x03 \x01(\t\"!\n\rOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\"\"\n\x0eOrderIdRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"K\n\x14OrderDetailsResponse\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x12\n\norder_date\x18\x03 \x01(\t\"\x1e\n\x0bUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"&\n\x14OrderHistoryResponse\x12\x0e\n\x06titles\x18\x01 \x03(\t2\x91\x02\n\x0fOrderManagement\x12K\n\nPlaceOrder\x12\x1d.ordermanagement.OrderRequest\x1a\x1e.ordermanagement.OrderResponse\x12Y\n\x0fGetOrderDetails\x12\x1f.ordermanagement.OrderIdRequest\x1a%.ordermanagement.OrderDetailsResponse\x12V\n\x0fGetOrderHistory\x12\x1c.ordermanagement.UserRequest\x1a%.ordermanagement.OrderHistoryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_management_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERREQUEST']._serialized_start=43
  _globals['_ORDERREQUEST']._serialized_end=107
  _globals['_ORDERRESPONSE']._serialized_start=109
  _globals['_ORDERRESPONSE']._serialized_end=142
  _globals['_ORDERIDREQUEST']._serialized_start=144
  _globals['_ORDERIDREQUEST']._serialized_end=178
  _globals['_ORDERDETAILSRESPONSE']._serialized_start=180
  _globals['_ORDERDETAILSRESPONSE']._serialized_end=255
  _globals['_USERREQUEST']._serialized_start=257
  _globals['_USERREQUEST']._serialized_end=287
  _globals['_ORDERHISTORYRESPONSE']._serialized_start=289
  _globals['_ORDERHISTORYRESPONSE']._serialized_end=327
  _globals['_ORDERMANAGEMENT']._serialized_start=330
  _globals['_ORDERMANAGEMENT']._serialized_end=603
# @@protoc_insertion_point(module_scope)
