# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_auth.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fuser_auth.proto\x12\tuser_auth\"5\n\x0fUserCredentials\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\".\n\x0c\x41uthResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t2\x91\x01\n\x08UserAuth\x12\x43\n\x0cRegisterUser\x12\x1a.user_auth.UserCredentials\x1a\x17.user_auth.AuthResponse\x12@\n\tLoginUser\x12\x1a.user_auth.UserCredentials\x1a\x17.user_auth.AuthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERCREDENTIALS']._serialized_start=30
  _globals['_USERCREDENTIALS']._serialized_end=83
  _globals['_AUTHRESPONSE']._serialized_start=85
  _globals['_AUTHRESPONSE']._serialized_end=131
  _globals['_USERAUTH']._serialized_start=134
  _globals['_USERAUTH']._serialized_end=279
# @@protoc_insertion_point(module_scope)
